### ISSUE TITLE
Presentation Date Change - Brandon Badger

### ISSUE THREAD

**Issue by bmb122** [laboon/Capstone_Fall2018#115]
So I, without thinking, scheduled a set of date for my presentation even though I am presenting with another person, Tyler Handerhan. My date is currently this Friday, September 14,  and his is the 28 of September. He is out of the city for this Friday, so I wanted to move my presentation date to the 28th alongside him if that doesn't pose a big problem. Thanks!

**Comment by laboon** [comment]
Fixed in commit 86ae29fc80e53037029a681b14df3f9da36b672d, moved Brandon Badger and Tyler Handherhan together on the 28th
