### ISSUE TITLE
Project - Josh Koshy

### ISSUE THREAD

**Issue by Josh-Koshy** [laboon/Capstone_Fall2018#63]
### **Healthy Living App**

I have had fun working with front-end design on some personal projects over the summer and would like the opportunity to try to improve using this project. I am familiar with JavaScript and Python, and I am looking forward to learning more on Ruby. As for database management, I have also worked with PostgreSQL in the past and am currently working on learning Oracle through the Database Management Systems course here at Pitt. I have also worked with SQLAlchemy for handling information to be used on websites.

Personally, I have also been focused on creating a healthier lifestyle for myself. Over the summer, this included creating meal plans based on my calorie intake and shaping up my diet, as well as shaping my exercise plan more. I have also investigated the idea with a few friends on creating an app using React that focused mainly on exercise planning. I am also very familiar with similar apps within the marketplace that have achieved success.

### **Sheep and Goat Tracker**

As I've stated above, Ruby on Rails is a desireable language that I have wanted to learn more about. Continuing development for this project feels like a great way to quickly learn more of the language as well as supplement my own help at the same time. My grandfather was a farmer who has tended to sheep overseas, and I've recently just visited him for vacation. I am familiar with the lifestyle and process that my grandfather has to go through with tending to farm animals.

### **CampusGruv**

I haven't had much of a chance to work with the iOS platform, and this seems like a great opportunity to try and do so. I'm familiar with front-end design on seperate platforms and this seems like a great way to improve on my abilities. I like the idea of "a network of visually engaging 'campusfeeds'" and it sounds like a great project for a front-end developer to assess, test, and rework if necessary.

**Comment by laboon** [comment]
@Josh-Koshy you need to write your top three projects in the comments sections above (or leave a new comment with that information)

**Comment by Josh-Koshy** [comment]
Sorry, that was my mistake! I've updated it above.

**Comment by laboon** [comment]
👍
